- name: Deploying with Kubernetes
  hosts: all
  tasks:
    - name: Show ansible_user
      debug:
        msg: "The ansible_user is {{ ansible_user }}"

    - name: Clone the repository
      git:
        repo: https://github.com/shouryap1/Talent_Bridge_Kubernetes.git
        dest: /tmp/Talent_Bridge_Kubernetes
      

    - name: Apply Kubernetes manifests
      command: kubectl apply -f /tmp/Talent_Bridge_Kubernetes/kub