- name: Deploy Frontend and Backend with Kubernetes
  hosts: all
  tasks:
    - name: Show ansible_user
      debug:
        msg: "The ansible_user is {{ ansible_user }}"

    - name: Clone Repository
      include_role:
        name: clone_repo

    - name: Deploy Frontend Resources
      include_role:
        name: deploy_frontend

    - name: Deploy Backend Resources
      include_role:
        name: deploy_backend
