apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-react-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-react-app
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 1  # Scale if average CPU utilization exceeds 50%
